#ifndef STDLIB
#include <stdlib.h>
#define STDLIB
#endif

// Number used for large sample sizes
#define BIGNUM 2000000

long double rand1() {
	return (long double) rand() / (long double) RAND_MAX;
}

// Gives the mean of a sample of BIGNUM random values generated by the given function
double sample_mean(int (*function)()) {
	double ret = 0;
	int current_sample;
	for (int i = 0; i < BIGNUM; i++) {
		current_sample = (*function)();
		ret += current_sample;
	}
	return ret / BIGNUM;
}