#ifndef STATISTICS_H
#define STATISTICS_H

// Number used for large sample sizes
#define BIGNUM 2000000

// Function that generates a random number between 0 and 1
long double rand1();

// Sample Mean function:
// Gives the mean of a sample of BIGNUM random values generated by the given function.

// Discrete variable with no parameter
double sample_mean(int (*function)());

// Discrete variable with integer parameter
double sample_mean(int (*function)(int), int i);

// Continuous variable with no parameter
double sample_mean(double (*function)());

// Continuous variable with floating point parameter
long double sample_mean(double (*function)(double), double d);

// Generates a random number with an exponential distribution
double exponential(double rate);

#endif